version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: calagopus-heavy-aio_web_1
      APP_PORT: 8000

  web:
    image: ghcr.io/calagopus/panel:1.2.2-heavy-aio@sha256:c5fe8f0ccd0dbb72840b5229c57003d72216dc10c755d76c0a0b8039629aa5e8
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    environment:
      TZ: Europe/Berlin
      REDIS_URL: redis://cache
      DATABASE_URL: postgresql://panel:${APP_CALAGOPUS_PANEL_HEAVY_AIO_DB_PASSWORD}@db/panel
      DATABASE_MIGRATE: "true"
      PORT: "8000"
      DOCKER_HOST: unix:///var/run/docker.sock
      AIO_BASE_WINGS_CONFIGURATION: /wings-config.yml
      APP_DEBUG: "false"
      APP_LOG_DIRECTORY: /var/log/calagopus
      APP_PRIMARY: "true"
      APP_ENABLE_WINGS_PROXY: "true"
      APP_ENCRYPTION_KEY: ${APP_SEED}
      APP_TRUSTED_PROXIES: ${NETWORK_IP}/16
      APP_USE_DECRYPTION_CACHE: "true"
      APP_USE_INTERNAL_CACHE: "true"
    volumes:
      # --- panel
      - ${APP_DATA_DIR}/data/panel:/var/lib/calagopus
      - ${APP_DATA_DIR}/data/logs:/var/log/calagopus

      # --- extensions
      - ${APP_DATA_DIR}/data/build/binaries:/app/binaries
      - ${APP_DATA_DIR}/data/build/translations:/app/translations
      - ${APP_DATA_DIR}/data/build/extensions:/app/extensions
      - ${APP_DATA_DIR}/data/build/extension-migrations:/app/repo/database/extension-migrations

      # --- wings
      - ${APP_DATA_DIR}/data/wings-config.yml:/wings-config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data/wings-etc:/etc/calagopus-wings
      - ${APP_DATA_DIR}/data/wings-logs:/var/log/calagopus-wings
      - ${APP_DATA_DIR}/data/wings:/var/lib/calagopus-wings
      - ${APP_DATA_DIR}/data/wings-tmp:/tmp/calagopus-wings
    ports:
      - "8000:8000"
      - "2022:2022"

  db:
    image: ghcr.io/calagopus/pgautoupgrade:18.4-alpine@sha256:65a9f085cd81a93b7f38bc49651d0a6c7183e36984dcee9b1a3c5ddf3c1e319c
    restart: on-failure
    environment:
      TZ: Europe/Berlin
      POSTGRES_USER: panel
      POSTGRES_PASSWORD: ${APP_CALAGOPUS_PANEL_HEAVY_AIO_DB_PASSWORD}
      POSTGRES_DB: panel
      PGDATA: /data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U panel -d panel"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/data

  cache:
    image: ghcr.io/calagopus/valkey:9.1.1@sha256:48267fca9907c48d9654b8c3f85fe7b851585743107460bc27c1949a25251f7a
    restart: on-failure
    command: --protected-mode no --save 60 1
    environment:
      TZ: Europe/Berlin
    volumes:
      - ${APP_DATA_DIR}/data/cache:/data
