#!/usr/bin/env bash
set -euo pipefail

APP_DIR="${APP_DATA_DIR:-$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")}"
DATA_DIR="${APP_DIR}/data"

mkdir -p \
  "${DATA_DIR}/postgres" \
  "${DATA_DIR}/cache" \
  "${DATA_DIR}/panel" \
  "${DATA_DIR}/logs" \
  "${DATA_DIR}/wings" \
  "${DATA_DIR}/wings-etc" \
  "${DATA_DIR}/wings-logs" \
  "${DATA_DIR}/wings-tmp" \
  "${DATA_DIR}/build/binaries" \
  "${DATA_DIR}/build/translations" \
  "${DATA_DIR}/build/extensions" \
  "${DATA_DIR}/build/extension-migrations"

[ -e "${DATA_DIR}/wings-config.yml" ] || touch "${DATA_DIR}/wings-config.yml"
